---
title: java 异常
date: 2022-05-20 14:28:16
permalink: /pages/dadbde7e55222274
category:
  - Java
  - java 基础
tag:
  - 异常
author:
  name: Vance L
  link: https://github.com/Dovahkiin8625



---



# Java 基础 - 异常  <font color="#999">Java Exception </font>

[[TOC]]

## 1 基础语法 <font color="#999">Basic Grammar </font>

### 1.1 异常申明 `throws`

:page_facing_up: `testThrows()`

```java
    @Test
    public void testThrows(){
        try {
            readFile("");
        } catch (IOException e) {
            System.out.println("异常申明测试: "+e.toString());
        }
    }
    private static void readFile(String filePath) throws IOException{
        File file = new File(filePath);
        BufferedReader reader = new BufferedReader(new FileReader(file));
        String result;
        while((result = reader.readLine())!=null) {
            System.out.println(result);
        }
        reader.close();
    }
```

:heavy_check_mark: Output

```
异常申明测试: java.io.FileNotFoundException:  (系统找不到指定的路径。)
```

### 1.2 异常抛出 `throw`

:page_facing_up: `testThrow()`

```java
    @Test
    public void testThrow(){
        try{
            readObjProp("TEST");
            readObjProp(null);
        }catch (NullPointerException e){
            System.out.println("异常抛出测试: "+e.getClass()+"\n"+e.toString());
        }
    }
    private static void readObjProp(String str){
        try{
            System.out.println(str.toLowerCase(Locale.ROOT));
        }catch (NullPointerException e){
            throw(e);
        }
    }
```

:heavy_check_mark: Output

```
test
异常抛出测试: class java.lang.NullPointerException
java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because "str" is null

```

### 1.3 异常捕获 `try...catch...finally`



基本的异常语法为

```java
try {                        
    //执行程序代码，可能会出现异常                 
} catch(Exception e) {   
    //捕获异常并处理   
} finally {
    //必执行的代码
}
  
```

语句执行顺序

> * 当try没有捕获到异常时：try语句块中的语句逐一被执行，程序将跳过catch语句块，执行finally语句块和其后的语句；
>
> * 当try捕获到异常，catch语句块里没有处理此异常的情况：此异常将会抛给JVM处理，finally语句块里的语句还是会被执行，但finally语句块后的语句不会被执行；
>
> * 当try捕获到异常，catch语句块里有处理此异常的情况：程序将跳到catch语句块，并与catch语句块逐一匹配，找到与之对应的处理程序，其他的catch语句块将不会被执行，而try语句块中，出现异常之后的语句也不会被执行，catch语句块执行完后，执行finally语句块里的语句，最后执行finally语句块后的语句；
>
> **注意**: finally块总会执行

:page_facing_up: `testCatch()`

```java
    @Test
    public void testCatch(){
        String test = exceptionOrder("TEST");
        System.out.println("方法返回结果: "+test);
        String test1 = exceptionOrder(null);
        System.out.println("方法返回结果: "+test1);

    }
    private static String  exceptionOrder(String str){
        try{
            System.out.println("执行try语句");
            String s = str.toLowerCase(Locale.ROOT);
            return "try";
        }catch (Exception e){
            System.out.println("执行catch"+e.toString());
            return "catch";
        }finally {
            System.out.println("执行finally");
        }
    }
```

:heavy_check_mark: Output

```
执行try语句
执行finally
方法返回结果: try
执行try语句
执行catchjava.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because "str" is null
执行finally
方法返回结果: catch
```

可以看到此处,不管是有无异常,在方法返回前,都会执行`finally`中的语句,注意不要再`finally`块中返回,因为这样会使得`try`和`catch`中的`return`语句不能被执行,此处特性与`python`中的异常处理一致.

:page_facing_up: `TestCatch()`

```
执行try语句
执行finally
方法返回结果: finally
执行try语句
执行catchjava.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because "str" is null
执行finally
方法返回结果: finally
```

## 2 异常注意事项 <font color="#999">Announcements</font>

### 2.1 只针对不正常的情况下才使用异常

* 异常机制的设计初衷是用于不正常的情况，所以很少会会JVM实现试图对它们的性能进行优化。所以，创建、抛出和捕获异常的开销是很昂贵的。

* 把代码放在try-catch中返回阻止了JVM实现本来可能要执行的某些特定的优化。

* 对数组进行遍历的标准模式并不会导致冗余的检查，有些现代的JVM实现会将它们优化掉。

### 2.2 清理资源

**在`finally`块中清理资源**

:page_facing_up: `testFreeResourceUseFinally()`

```java
    @Test
    public void testFreeResourceUseFinally(){
        String filePath = "Exception/exceptionTestFile.txt";
        ClassPathResource classPathResource = new ClassPathResource(filePath);
        String path = classPathResource.getPath();
        FileInputStream fileInputStream =null;
        try{
            File file = classPathResource.getFile();
            logger.info("path: "+path);
            logger.info("file: "+file);
            fileInputStream = new FileInputStream(file);
            byte[] bytes = fileInputStream.readAllBytes();
            logger.info(new String(bytes));
        }catch (Exception e){
            logger.error("异常: " + e.toString());
        }finally {
            if(fileInputStream!=null){
                try{
                    fileInputStream.close();
                    logger.info("关闭文件流");
                }catch (IOException e){
                    logger.error("异常: "+e.toString());
                }
            }
        }
    }
```

:heavy_check_mark: Output

```java
2022-05-26 10:10:20 - INFO - path: Exception/exceptionTestFile.txt
2022-05-26 10:10:20 - INFO - file: E:\.JavaSpace\javaLearn\JavaBasic\target\classes\Exception\exceptionTestFile.txt
2022-05-26 10:10:20 - INFO - Hello World!
2022-05-26 10:10:20 - INFO - 关闭文件流
```

当读取的文件不存在， 设置 `String filePath = "Exception/exceptionTestFile1.txt";`

:heavy_check_mark: Output

```
2022-05-26 10:16:19 - ERROR- 异常: java.io.FileNotFoundException: class path resource [Exception/exceptionTestFile1.txt] cannot be resolved to URL because it does not exist
```

**try-with-resource 语法 **

:page_facing_up: `testFreeResourceUseTry()`

```java
    @Test
    public void testFreeResourceUseTry(){
        String filePath = "Exception/exceptionTestFile.txt";
        ClassPathResource classPathResource = new ClassPathResource(filePath);
        try(FileInputStream fileInputStream = new FileInputStream(classPathResource.getFile())){
            logger.info(new String(fileInputStream.readAllBytes()));
        } catch (IOException e){
            logger.error("异常: "+e.toString());
        }
    }
```

:heavy_check_mark: Output

```
2022-05-26 10:17:47 - INFO - Hello World!
```

当读取的文件不存在， 设置 `String filePath = "Exception/exceptionTestFile1.txt";`

:heavy_check_mark: Output

```
2022-05-26 10:19:49 - ERROR- 异常: java.io.FileNotFoundException: class path resource [Exception/exceptionTestFile1.txt] cannot be resolved to URL because it does not exist
```

### 2.3 尽量使用标准异常

* 它使得你的API更加易于学习和使用，因为它与程序员原来已经熟悉的习惯用法是一致的。

* 对于用到这些API的程序而言，它们的可读性更好，因为它们不会充斥着程序员不熟悉的异常。

* 异常类越少，意味着内存占用越小，并且转载这些类的时间开销也越小。

### 2.4 对异常进行文档说明

当在方法上声明抛出异常时，也需要进行文档说明。目的是为了给调用者提供尽可能多的信息，从而可以更好地避免或处理异常。

### 2.5 优先捕获最具体的异常

只有匹配异常的第一个 catch 块会被执行。

### 2.6 不要捕获 `Throwable` 类

如果在 `catch` 子句中使用 `Throwable` ，它不仅会捕获所有异常，也将捕获所有的错误。JVM 抛出错误，指出不应该由应用程序处理的严重问题。 典型的例子是 `OutOfMemoryError` 或者 `StackOverflowError` 。两者都是由应用程序控制之外的情况引起的，无法处理。

所以，最好不要捕获 `Throwable` ，除非你确定自己处于一种特殊的情况下能够处理错误。

### 2.7 不要忽略异常

不能catch块中不做任何处理或者记录日志，合理的做法是至少要记录异常的信息。

### 2.8 不要既捕获异常又抛出异常

仅仅当想要处理异常时才去捕获，否则只需要在方法签名中声明让调用者去处理。

### 2.9 不要使用异常来控制程序流程

不应该使用异常控制应用的执行流程，例如，本应该使用if语句进行条件判断的情况下，你却使用异常处理，这是非常不好的习惯，会严重影响应用的性能。

### 2.10 包装异常时不要丢弃原始异常

### 2.11 不要在`finally`块中使用`return`

try块中的return语句执行成功后，并不马上返回，而是继续执行finally块中的语句，如果此处存在return语句，则在此直接返回，无情丢弃掉try块中的返回点。

