---
title: python 异常
date: 2022-03-10 22:15:53
permalink: /pages/7ce140/
categories:
  - Python
  - python 基础
tags:
  - 异常
---
##  异常语句
[异常捕捉](#异常捕捉)<br>
[抛出异常](#抛出异常)<br>
[断言语句](#断言语句)<br>

## 异常捕捉
[回到顶部](#异常语句)

异常捕捉可以使用 try/except 语句,


try 语句按照如下方式工作；
1. 执行 try 子句（在关键字 try 和关键字 except 之间的语句）。
2. 如果没有异常发生，忽略 except 子句，try 子句执行后结束。
3. 如果在执行 try 子句的过程中发生了异常，那么 try 子句余下的部分将被忽略。如果异常的类型和 except 之后的名称相符，那么对应的 except 子句将被执行。
4. 如果一个异常没有与任何的 excep 匹配，那么这个异常将会传递给上层的 try 中。


```python
try:
    print(1+"1")
except SyntaxError:
    print("1")
except TypeError:
    print("2")
except:
    print(3)
```

    2


一个except子句可以同时处理多个异常，这些异常将被放在一个括号里成为一个元组


```python
try:
    print(1+"1")
except (SyntaxError, TypeError):
    print("1")
```

    1


try/except 语句还有一个可选的 else、finally 子句，如果使用这个子句，那么必须放在所有的 except 子句之后
- else 子句将在 try 子句没有发生任何异常的时候执行。
- finally 语句无论是否发生异常都将执行最后的代码。


```python
try:
    1 + 2
    print("try")
except:
    print("except")
else:
    print("else")
finally:
    print("finally")
```

    try
    else
    finally



```python
try:
    1 + "2"
    print("try")
except:
    print("except")
else:
    print("else")
finally:
    print("finally")
```

    except
    finally



```python

```

## 抛出异常
[回到顶部](#异常语句)

使用 raise 语句抛出一个指定的异常


```python
def foo(s):
    if s > 5:
        raise Exception('值不能大于 5')
    else:
        print(s)
```


```python
foo(3)
```

    3



```python
foo(6)
```


    ---------------------------------------------------------------------------
    
    Exception                                 Traceback (most recent call last)
    
    <ipython-input-5-d07199591eb7> in <module>
    ----> 1 foo(6)


    <ipython-input-3-3fe5ae8f680a> in foo(s)
          1 def foo(s):
          2     if s > 5:
    ----> 3         raise Exception('值不能大于 5')
          4     else:
          5         print(s)


    Exception: 值不能大于 5



```python

```

## 断言语句
[回到顶部](#异常语句)

assert（断言）用于判断一个表达式，在表达式条件为 false 的时候触发异常。


```python
assert 1>2
```


    ---------------------------------------------------------------------------
    
    AssertionError                            Traceback (most recent call last)
    
    <ipython-input-3-1e5504265e0c> in <module>
    ----> 1 assert 1>2


    AssertionError: 



```python

```
